ChatCompletion(
    id='chatcmpl-92ZHej5GG8zNxZuul9wrY3YBkRZSv', 
    choices=[
            Choice(
                    finish_reason='stop', 
                    index=0, 
                    logprobs=None, 
                    message=ChatCompletionMessage(
                        content='Nairobi', 
                        role='assistant', 
                        function_call=None, 
                        tool_calls=None
                        )
                    )
            ], 
    created=1710399314, 
    model='gpt-3.5-turbo-0125', 
    object='chat.completion', 
    system_fingerprint='fp_4f0b692a78', 
    usage=CompletionUsage(
                            completion_tokens=2, 
                            prompt_tokens=13, 
                            total_tokens=15
                        )
)